In [44]:
import pandas as pd

- [ ] Explode on team events

In [ ]:
EVENT_NAMES = ['COMPOUND WOMEN INDIVIDUAL',
 'RECURVE MEN INDIVIDUAL',
 'RECURVE WOMEN INDIVIDUAL',
 'COMPOUND MEN INDIVIDUAL',
 'COMPOUND MIXED TEAM',
 'RECURVE MIXED TEAM',
 'RECURVE MEN TEAM',
 'COMPOUND MEN TEAM',
 'RECURVE WOMEN TEAM',
 'COMPOUND WOMEN TEAM',
 'INDIAN ROUND WOMEN TEAM',
 'INDIAN ROUND WOMEN INDIVIDUAL',
 'INDIAN ROUND MEN INDIVIDUAL',
 'INDIAN ROUND MEN TEAM',
 'INDIAN ROUND MIXED TEAM',
 'RECURVE MEN',
 'RECURVE WOMEN',
 'COMPOUND MEN',
 'COMPOUND WOMEN',
 'INDIAN ROUND MEN',
 'INDIAN ROUND WOMEN',
 'RECURVE MIX TEAM',
 'COMPOUND MIX TEAM',
 'INDIAN ROUND MIX TEAM']

ROUND_NAMES = ['1/4 ELIMINATION',
 '1/4 FINAL',
 '1/8 ELIMINATION',
 '1/8 FINAL',
 'BRONZE MEDAL',
 'BRONZE MEDAL MATCH',
 'DATA NOT AVAILABLE',
 'FINAL',
 'GOLD MEDAL MATCH',
 'PRELIMINARY ROUND',
 'QUARTER-FINAL',
 'QUARTERFINAL',
 'ROUND 1',
 'ROUND 2',
 'ROUND OF 12',
 'ROUND OF 16',
 'ROUND OF 24',
 'ROUND OF 32',
 'ROUND OF 48',
 'ROUND OF 64',
 'ROUND OF 8',
 'SEMI-FINAL',
 'SEMIFINAL']


COUNTRY__CODES = {
    # Already codes (keep as-is)
    "KOR": "KOR", "KAZ": "KAZ", "INA": "IDN", "JPN": "JPN",
    "HKG": "HKG", "VIE": "VNM", "NEP": "NPL", "SRI": "LKA",
    "TPE": "TPE", "MYA": "MMR", "QAT": "QAT", "MAS": "MYS",
    "MGL": "MNG", "KSA": "SAU", "IND": "IND", "THA": "THA",
    "BAN": "BGD", "PRK": "PRK", "CHN": "CHN", "SGP": "SGP",
    "PHI": "PHL", "KGZ": "KGZ", "TJK": "TJK", "BHU": "BTN",
    "IRI": "IRN",

    # Full names → ISO3
    "South Korea": "KOR",
    "North Korea": "PRK",
    "India": "IND",
    "China": "CHN",
    "Japan": "JPN",
    "Indonesia": "IDN",
    "Malaysia": "MYS",
    "Iran": "IRN",
    "Kazakhstan": "KAZ",
    "Philippines": "PHL",
    "Thailand": "THA",
    "Hong Kong": "HKG",
    "Chinese Taipei": "TPE",
    
    
    "Mongolia": "MNG",
    "Bangladesh": "BGD",
    "Bhutan": "BTN",
    "Vietnam": "VNM",
    
    "Ukraine": "UKR",
    "Ivory Coast": "CIV",
    "Italy": "ITA",
    "Cuba": "CUB",
    "France": "FRA",
    "Chile": "CHL",
    "Brazil": "BRA",
    "Tonga": "TON",
    "Spain": "ESP",
    "Egypt": "EGY",
    "Germany": "DEU",
    "Colombia": "COL",
    "Netherlands": "NLD",
    "Slovakia": "SVK",
    "Venezuela": "VEN",
    "Great Britain": "GBR",
    "Australia": "AUS",
    "United States": "USA",
    "Libya": "LBY",
    "Belgium": "BEL",
    "Greece": "GRC",
    "Mexico": "MEX",
    
     "Zimbabwe": "ZWE",
    "Fiji": "FJI",
    "Nepal": "NPL",
    "Belarus": "BLR",
    "Malawi": "MWI",
    "Finland": "FIN",
    "Norway": "NOR",
    "Canada": "CAN",
    "GER": "DEU",
    "Kenya": "KEN",
    "Georgia": "GEO",
    "Russia": "RUS",
    
    "Denmark": "DNK",
    "Estonia": "EST",
    "Turkey": "TUR",
    "Israel": "ISR",
    "Romania": "ROU",
    "Moldova": "MDA",
    "Tunisia": "TUN",
    "Sweden": "SWE",
    "Slovenia": "SVN",
    "Hungary": "HUN",
    "Poland": "POL",
    "Virgin Islands": "VIR",
    "Luxembourg": "LUX",
    "Chad": "TCD",
    "Ecuador": "ECU",
    "Czech Republic": "CZE",
    
    "Puerto Rico": "PRI",
    "San Marino": "SMR",
    "Austria": "AUT",
    "Uzbekistan": "UZB",
    "Azerbaijan": "AZE",
    "Argentina": "ARG",
    "Guinea": "GIN",
    "El Salvador": "SLV",
    "South Africa": "ZAF"
}

# 2016 Olympic Games

In [46]:
df_1 = pd.read_csv('2016_olympics.csv')

In [47]:
df_1.head()

,championship_name,event,round_name,round,player_a,player_b,score_a,score_b,winner
0,Archery at the 2016 Summer Olympics,Men's individual,Section 1,Round of 64,W-j Kim (South Korea),G Sutherland (Zimbabwe),6,0,W-j Kim (South Korea)
1,Archery at the 2016 Summer Olympics,Men's individual,Section 1,Round of 64,R Ega Agatha (Indonesia),Y Xing (China),7,1,R Ega Agatha (Indonesia)
2,Archery at the 2016 Summer Olympics,Men's individual,Section 1,Round of 64,X Gu (China),S Duzelbayev (Kazakhstan),4,6,S Duzelbayev (Kazakhstan)
3,Archery at the 2016 Summer Olympics,Men's individual,Section 1,Round of 64,M Wijaya,M Nespoli (Italy),3,7,M Nespoli (Italy)
4,Archery at the 2016 Summer Olympics,Men's individual,Section 1,Round of 64,C-h Wei (Chinese Taipei),R Elder (Fiji),6,0,C-h Wei (Chinese Taipei)

In [48]:
df_1 = df_1.drop(columns=['round_name'],axis=1)
df_1.rename(columns={'round':'round_name'},inplace=True)

In [49]:
# Clean the event_name
df_1['event'].unique()

array(["Men's individual", "Women's individual", "Men's team",
       "Women's team"], dtype=object)

In [50]:
sorted(EVENT_NAMES)

['COMPOUND MEN',
 'COMPOUND MEN INDIVIDUAL',
 'COMPOUND MEN TEAM',
 'COMPOUND MIX TEAM',
 'COMPOUND MIXED TEAM',
 'COMPOUND WOMEN',
 'COMPOUND WOMEN INDIVIDUAL',
 'COMPOUND WOMEN TEAM',
 'INDIAN ROUND MEN',
 'INDIAN ROUND MEN INDIVIDUAL',
 'INDIAN ROUND MEN TEAM',
 'INDIAN ROUND MIX TEAM',
 'INDIAN ROUND MIXED TEAM',
 'INDIAN ROUND WOMEN',
 'INDIAN ROUND WOMEN INDIVIDUAL',
 'INDIAN ROUND WOMEN TEAM',
 'RECURVE MEN',
 'RECURVE MEN INDIVIDUAL',
 'RECURVE MEN TEAM',
 'RECURVE MIX TEAM',
 'RECURVE MIXED TEAM',
 'RECURVE WOMEN',
 'RECURVE WOMEN INDIVIDUAL',
 'RECURVE WOMEN TEAM']

In [51]:
event_standardization_dict = {
    "Men's individual recurve": "RECURVE MEN INDIVIDUAL",
    "Men's team recurve": "RECURVE MEN TEAM",
    "Men's team compound": "COMPOUND MEN TEAM",
    "Women's individual recurve": "RECURVE WOMEN INDIVIDUAL",
    "Women's team recurve": "RECURVE WOMEN TEAM",
    "Women's team compound": "COMPOUND WOMEN TEAM",
    'Mixed team recurve': 'RECURVE MIXED TEAM',
    'Mixed team compound': 'COMPOUND MIXED TEAM',
    
    "Men's individual": "INDIVIDUAL MEN",
    "Women's individual": "INDIVIDUAL WOMEN",
    "Men's team": "TEAM MEN",
    "Women's team": "TEAM WOMEN"
}
df_1['event'] = df_1['event'].map(event_standardization_dict)

In [52]:
df_1['round_name'].unique()

array(['Round of 64', 'Round of 32', 'Round of 16', 'Quarter-finals',
       'Semi-finals', 'Gold medal match', 'Bronze medal match',
       '1/32 eliminations', '1/16 eliminations', '1/8 eliminations',
       'Quarterfinals', 'Semifinals', 'Bronze Medal Match'], dtype=object)

In [53]:
## Standardizing the round names
round_standardization_dict = {
    'Quarterfinals': 'QUARTERFINAL',
    'Semifinals': 'SEMI-FINAL',
    'Gold medal match': 'GOLD MEDAL MATCH',
    'Bronze medal match': 'BRONZE MEDAL MATCH',
    '1/32 eliminations': '1/32 ELIMINATION',
    '1/16 eliminations': '1/16 ELIMINATION',
    '1/8 eliminations': '1/8 ELIMINATION',
    
    
    'Round of 64': "ROUND OF 64", 
    'Round of 32': "ROUND OF 32", 
    'Round of 16': "ROUND OF 16",
    'Quarter-finals': "QUARTER-FINALS",
    'Semi-finals': "SEMI-FINALS", 
    'Gold medal match': "GOLD MEDAL MATCH", 
    'Bronze medal match': "BRONZE MEDAL MATCH",
    '1/32 eliminations': "1/32 ELIMINATION",
    '1/16 eliminations': "1/16 ELIMINATION", 
    '1/8 eliminations': "1/8 ELIMINATION",
    'Quarterfinals': "QUARTERFINAL", 
    'Semifinals': "SEMI-FINAL", 
    'Bronze Medal Match': "BRONZE MEDAL MATCH"
}
df_1['round_name'] = df_1['round_name'].map(round_standardization_dict).fillna(df_1['round_name'])

In [54]:
df_1["player_a_countries"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["player_a_countries"] =  df_1["player_a_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1["player_b_countries"] = df_1["player_b"].str.findall(r"\(([^)]*)\)")
df_1["player_b_countries"] =  df_1["player_b_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

df_1["winner_countries"] = df_1["winner"].str.findall(r"\(([^)]*)\)")
df_1["winner_countries"] =  df_1["winner_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

In [55]:
df_1["player_b"] = df_1["player_b"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_b"] = (
    df_1["player_b"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

df_1["player_a"] = df_1["player_a"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_a"] = (
    df_1["player_a"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)


df_1["winner"] = df_1["winner"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["winner"] = (
    df_1["winner"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

In [56]:
## Explode the player_a and player_b columns to have one player per row
df_1 = df_1.assign(
    player_a=df_1["player_a"].str.split(" / ")
).explode("player_a").reset_index(drop=True)

df_1 = df_1.assign(
    player_b=df_1["player_b"].str.split(" / ")
).explode("player_b").reset_index(drop=True)

df_1 = df_1.assign(
    winner=df_1["winner"].str.split(" / ")
).explode("winner").reset_index(drop=True)

In [57]:
# df_1 = df_1.explode("countries").reset_index(drop=True)
df_1 = df_1.explode("player_b_countries").reset_index(drop=True)
df_1 = df_1.explode("winner_countries").reset_index(drop=True)
df_1 = df_1.explode("player_a_countries").reset_index(drop=True)

In [58]:
df_1['winner_country'] = df_1['winner_countries'].map(COUNTRY__CODES).fillna(df_1['winner_countries'])
df_1['player_b_country'] = df_1['player_b_countries'].map(COUNTRY__CODES).fillna(df_1['player_b_countries'])
df_1['player_a_country'] = df_1['player_a_countries'].map(COUNTRY__CODES).fillna(df_1['player_a_countries'])

In [62]:
df_1['winner_country'].unique()

array(['KOR', 'IDN', 'KAZ', 'ITA', 'TPE', 'THA', 'UKR', 'FRA', 'IND',
       'CUB', 'ESP', 'CHL', 'BRA', 'Turkey', 'NLD', 'VEN', 'AUS', 'DEU',
       'MYS', 'GBR', 'JPN', 'NOR', 'BEL', 'USA', 'CAN', 'RUS', 'TUR',
       'MEX', 'CHN', nan, 'SVK', 'MDA', 'PRK', 'SWE'], dtype=object)

In [63]:
df_1['winner_country'].unique()

array(['KOR', 'IDN', 'KAZ', 'ITA', 'TPE', 'THA', 'UKR', 'FRA', 'IND',
       'CUB', 'ESP', 'CHL', 'BRA', 'Turkey', 'NLD', 'VEN', 'AUS', 'DEU',
       'MYS', 'GBR', 'JPN', 'NOR', 'BEL', 'USA', 'CAN', 'RUS', 'TUR',
       'MEX', 'CHN', nan, 'SVK', 'MDA', 'PRK', 'SWE'], dtype=object)

In [64]:
df_1[['championship_name', 'event', 'round_name', 'player_a','player_a_country','score_a', 'player_b','player_b_country','score_b', 'winner', 'winner_country']].to_csv('olympics_2016_cleaned.csv', index=False)

# 2021 Olympic Games

In [122]:
# df_1.to_csv('asian_games_2018_cleaned.csv', index=False)

In [123]:
df_1 = pd.read_csv('2021_olympics.csv')

In [124]:
df_1.head()

,championship_name,event,round_name,round,player_a,player_b,score_a,score_b,winner
0,Archery at the 2020 Summer Olympics,Women's individual,Section 1,Round of 64,An S (South Korea),M Hourtou (Chad),6,2,An S (South Korea)
1,Archery at the 2020 Summer Olympics,Women's individual,Section 1,Round of 64,A M dos Santos (Brazil),A Vázquez (Mexico),6,4,A M dos Santos (Brazil)
2,Archery at the 2020 Summer Olympics,Women's individual,Section 1,Round of 64,C Kaufhold (United States),I de Velasco (Spain),7,3,C Kaufhold (United States)
3,Archery at the 2020 Summer Olympics,Women's individual,Section 1,Round of 64,Đỗ T A N (Vietnam),R Hayakawa (Japan),5 7,6 8,R Hayakawa (Japan)
4,Archery at the 2020 Summer Olympics,Women's individual,Section 1,Round of 64,D Kumari (India),Karma (Bhutan),6,0,D Kumari (India)

In [125]:
df_1 = df_1.drop(columns=['round_name'],axis=1)
df_1.rename(columns={'round':'round_name'},inplace=True)

In [126]:
# Clean the event_name
df_1['event'].unique()

array(["Women's individual", "Men's individual", 'Mixed team',
       "Women's team", "Men's team"], dtype=object)

In [127]:
sorted(EVENT_NAMES)

['COMPOUND MEN',
 'COMPOUND MEN INDIVIDUAL',
 'COMPOUND MEN TEAM',
 'COMPOUND MIX TEAM',
 'COMPOUND MIXED TEAM',
 'COMPOUND WOMEN',
 'COMPOUND WOMEN INDIVIDUAL',
 'COMPOUND WOMEN TEAM',
 'INDIAN ROUND MEN',
 'INDIAN ROUND MEN INDIVIDUAL',
 'INDIAN ROUND MEN TEAM',
 'INDIAN ROUND MIX TEAM',
 'INDIAN ROUND MIXED TEAM',
 'INDIAN ROUND WOMEN',
 'INDIAN ROUND WOMEN INDIVIDUAL',
 'INDIAN ROUND WOMEN TEAM',
 'RECURVE MEN',
 'RECURVE MEN INDIVIDUAL',
 'RECURVE MEN TEAM',
 'RECURVE MIX TEAM',
 'RECURVE MIXED TEAM',
 'RECURVE WOMEN',
 'RECURVE WOMEN INDIVIDUAL',
 'RECURVE WOMEN TEAM']

In [128]:
event_standardization_dict = {
    "Men's individual recurve": "RECURVE MEN INDIVIDUAL",
    "Men's team recurve": "RECURVE MEN TEAM",
    "Men's team compound": "COMPOUND MEN TEAM",
    "Women's individual recurve": "RECURVE WOMEN INDIVIDUAL",
    "Women's team recurve": "RECURVE WOMEN TEAM",
    "Women's team compound": "COMPOUND WOMEN TEAM",
    'Mixed team recurve': 'RECURVE MIXED TEAM',
    'Mixed team compound': 'COMPOUND MIXED TEAM',
    
    "Men's individual": "INDIVIDUAL MEN",
    "Women's individual": "INDIVIDUAL WOMEN",
    "Men's team": "TEAM MEN",
    "Women's team": "TEAM WOMEN",
    
    "Mixed team" : "MIXED TEAM"
}
df_1['event'] = df_1['event'].map(event_standardization_dict).fillna(df_1['event'])

In [129]:
df_1['event'].unique()

array(['INDIVIDUAL WOMEN', 'INDIVIDUAL MEN', 'MIXED TEAM', 'TEAM WOMEN',
       'TEAM MEN'], dtype=object)

In [130]:
## Standardizing the round names
round_standardization_dict = {
    'Quarterfinals': 'QUARTERFINAL',
    'Semifinals': 'SEMI-FINAL',
    'Gold medal match': 'GOLD MEDAL MATCH',
    'Bronze medal match': 'BRONZE MEDAL MATCH',
    '1/32 eliminations': '1/32 ELIMINATION',
    '1/16 eliminations': '1/16 ELIMINATION',
    '1/8 eliminations': '1/8 ELIMINATION',
    
    
    'Round of 64': "ROUND OF 64", 
    'Round of 32': "ROUND OF 32", 
    'Round of 16': "ROUND OF 16",
    'Quarter-finals': "QUARTER-FINALS",
    'Semi-finals': "SEMI-FINALS", 
    'Gold medal match': "GOLD MEDAL MATCH", 
    'Bronze medal match': "BRONZE MEDAL MATCH",
    '1/32 eliminations': "1/32 ELIMINATION",
    '1/16 eliminations': "1/16 ELIMINATION", 
    '1/8 eliminations': "1/8 ELIMINATION",
    'Quarterfinals': "QUARTERFINAL", 
    'Semifinals': "SEMI-FINAL", 
    'Bronze Medal Match': "BRONZE MEDAL MATCH"
}
df_1['round_name'] = df_1['round_name'].map(round_standardization_dict).fillna(df_1['round_name'])

In [131]:
df_1['round_name'].unique()

array(['ROUND OF 64', 'ROUND OF 32', 'ROUND OF 16', 'QUARTER-FINALS',
       'SEMI-FINALS', 'GOLD MEDAL MATCH', 'BRONZE MEDAL MATCH',
       '1/8 ELIMINATION'], dtype=object)

In [132]:
df_1["player_a_countries"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["player_a_countries"] =  df_1["player_a_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1["player_b_countries"] = df_1["player_b"].str.findall(r"\(([^)]*)\)")
df_1["player_b_countries"] =  df_1["player_b_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

df_1["winner_countries"] = df_1["winner"].str.findall(r"\(([^)]*)\)")
df_1["winner_countries"] =  df_1["winner_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

In [133]:
df_1["player_b"] = df_1["player_b"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_b"] = (
    df_1["player_b"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

df_1["player_a"] = df_1["player_a"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_a"] = (
    df_1["player_a"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)


df_1["winner"] = df_1["winner"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["winner"] = (
    df_1["winner"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

In [134]:
## Explode the player_a and player_b columns to have one player per row
df_1 = df_1.assign(
    player_a=df_1["player_a"].str.split(" / ")
).explode("player_a").reset_index(drop=True)

df_1 = df_1.assign(
    player_b=df_1["player_b"].str.split(" / ")
).explode("player_b").reset_index(drop=True)

df_1 = df_1.assign(
    winner=df_1["winner"].str.split(" / ")
).explode("winner").reset_index(drop=True)

In [135]:
df_1['player_a'].unique()

array(['An S', 'A M dos Santos', 'C Kaufhold', 'Đỗ T A N', 'D Kumari',
       'A Pavlova', 'M Jager', 'A Ingley', 'M Brown', 'M Amaistroaie',
       'Lin C-e', 'R Pärnat', 'L Barbelin', 'S Gomboeva',
       'K Dziominskaya', 'K Kazlouskaya', 'Kang C-y', 'V Marchenko',
       'Y Anagöz', 'A Mîrca', 'M Kroppen', 'S Mashayikh', 'Tan Y-t',
       'R Elwalid', 'B Pitman', 'E Osipova', 'A Yamauchi', 'H Marusava',
       'L Boari', 'C Bjerendal', 'S Bettles', 'N Folkard', 'M Nakamura',
       'A Adam', 'Wu JX', 'An San', 'Elena Osipova', 'Mackenzie Brown',
       'Kim J-d', 'F Unruh', 'R Shana', 'D Olaru', 'D Gankin',
       'Ž Ravnikar', 'P Huston', 'J-C Valladont', "M D'Almeida",
       'M Nespoli', 'H Muto', 'T Rai', 'Wei C-h', 'Nguyễn H P V',
       'Wang DP', 'A Vikström', 'J Williams', 'M L Balogh', 'I Shanny',
       'P Plihon', 'K Mohamad', 'Tang C-c', 'Oh J-h', 'A Das',
       'L Álvarez', 'T Chirault', 'Li JL', 'J de Smedt', 'I Abdullin',
       'S Napłoszek', 'T Furukawa', 'Wei SX', 'T Worth', "N D'Amour",
       'J Henckels', 'R E Agatha', 'J Wukie', 'P Jadhav', 'M Vaziri',
       'R Tyack', 'M Gazoz', 'Mauro Nespoli', 'Takaharu Furukawa',
       'Tang Chih-chun', 'Kim Je-deok', 'Pravin Jadhav', 'Deepika Kumari',
       'Wei Shaoxuan', 'Yang Xiaolei', 'Florian Unruh',
       'Michelle Kroppen', 'Hiroki Muto', 'Azusa Yamauchi',
       'Chiara Rebagliati', 'Mete Gazoz', 'Yasemin Anagöz',
       'Riau Ega Agatha', 'Diananda Choirunisa', 'Patrick Huston',
       'Sarah Bettles', 'Pierre Plihon', 'Lisa Barbelin', 'Steve Wijler',
       'Gabriela Schloesser', 'Luis Álvarez', 'Alejandra Valencia',
       'Jang Min-hee', 'Kang Chae-young', 'Karyna Kazlouskaya',
       'Hanna Marusava', 'Karyna Dziominskaya',
       'Jennifer Mucino-Fernandez', 'Casey Kaufhold', 'Charline Schwarz',
       'Lisa Unruh', 'Svetlana Gomboeva', 'Ksenia Perova', 'Atanu Das',
       'Tarundeep Rai', 'Jack Williams', 'Brady Ellison', 'Jacob Wukie',
       'David Barnes', 'Ryan Tyack', 'Taylor Worth', 'Arif Dwi Pangestu',
       'Alviyanto Prastyadi', 'Kim Woo-jin', 'Oh Jin-hyek', 'Li Jialun',
       'Wang Dapeng', 'Tom Hall', 'James Woodgate', 'Deng Yu-cheng',
       'Wei Chun-heng', 'Yuki Kawata'], dtype=object)

In [136]:
# df_1 = df_1.explode("countries").reset_index(drop=True)
df_1 = df_1.explode("player_b_countries").reset_index(drop=True)
df_1 = df_1.explode("winner_countries").reset_index(drop=True)
df_1 = df_1.explode("player_a_countries").reset_index(drop=True)

In [137]:
df_1['winner_country'] = df_1['winner_countries'].map(COUNTRY__CODES).fillna(df_1['winner_countries'])
df_1['player_b_country'] = df_1['player_b_countries'].map(COUNTRY__CODES).fillna(df_1['player_b_countries'])
df_1['player_a_country'] = df_1['player_a_countries'].map(COUNTRY__CODES).fillna(df_1['player_a_countries'])

In [138]:
df_1['player_b_country'].unique()

array(['TCD', 'MEX', 'ESP', 'JPN', 'BTN', 'USA', 'IDN', 'ROC', 'BRA',
       'IND', 'DEU', 'CHN', 'GRC', 'SVK', 'ITA', 'NLD', 'BGD', 'EST',
       'TPE', 'ECU', 'CAN', 'UKR', 'GBR', 'TUR', 'MNG', 'POL', 'COL',
       'CZE', 'KOR', 'BLR', 'MWI', 'EGY', nan, 'ISR', 'KAZ', 'MYS', 'FRA',
       'TUN', 'AUS', 'CHL'], dtype=object)

In [139]:
df_1['winner_country'].unique()

array(['KOR', 'BRA', 'USA', 'JPN', 'IND', 'DNK', 'ROC', 'CHN', 'TPE',
       'EST', 'FRA', 'NLD', 'BLR', 'MEX', 'UKR', 'TUR', 'DEU', 'GBR',
       'ITA', nan, 'BGD', 'CAN', 'KAZ', 'ISR', 'MYS', 'AUS', 'IDN'],
      dtype=object)

In [140]:
df_1['player_a_country'].unique()

array(['KOR', 'BRA', 'USA', 'VNM', 'IND', 'UKR', 'DNK', 'AUS', 'ROU',
       'TPE', 'EST', 'FRA', 'ROC', 'BLR', 'TUR', 'MDA', 'DEU', 'MYS',
       'TUN', 'GBR', 'JPN', 'ITA', 'SWE', 'EGY', 'CHN', nan, 'BGD', 'KAZ',
       'SVN', 'FIN', 'HUN', 'ISR', 'MEX', 'POL', 'VIR', 'LUX', 'IDN',
       'IRN', 'NLD'], dtype=object)

In [141]:
df_1[['championship_name', 'event', 'round_name', 'player_a','player_a_country','score_a', 'player_b','player_b_country','score_b', 'winner', 'winner_country']].to_csv('olympics_2021_cleaned.csv', index=False)

# 2024 Olympics

In [182]:
df_1 = pd.read_csv('2024_olympics.csv')

In [183]:
df_1.head()

,championship_name,event,round_name,round,player_a,player_b,score_a,score_b,winner
0,Archery at the 2024 Summer Olympics,Women's individual,Section 1,Round of 64,Lim S-h (South Korea),A Rivera (Puerto Rico),6,0,Lim S-h (South Korea)
1,Archery at the 2024 Summer Olympics,Women's individual,Section 1,Round of 64,V Chénier (Canada),R Octavia (Indonesia),2,6,R Octavia (Indonesia)
2,Archery at the 2024 Summer Olympics,Women's individual,Section 1,Round of 64,A Cordeau (France),D Baránková (Slovakia),7,3,A Cordeau (France)
3,Archery at the 2024 Summer Olympics,Women's individual,Section 1,Round of 64,M Havers (Great Britain),E Canales (Spain),6,0,M Havers (Great Britain)
4,Archery at the 2024 Summer Olympics,Women's individual,Section 1,Round of 64,Li JM (China),K D Andersen (Denmark),6,0,Li JM (China)

In [184]:
df_1 = df_1.drop(columns=['round_name'],axis=1)
df_1.rename(columns={'round':'round_name'},inplace=True)

In [185]:
# Clean the event_name
df_1['event'].unique()

array(["Women's individual", "Men's individual", "Women's team",
       "Men's team", 'Mixed team'], dtype=object)

In [186]:
sorted(EVENT_NAMES)

['COMPOUND MEN',
 'COMPOUND MEN INDIVIDUAL',
 'COMPOUND MEN TEAM',
 'COMPOUND MIX TEAM',
 'COMPOUND MIXED TEAM',
 'COMPOUND WOMEN',
 'COMPOUND WOMEN INDIVIDUAL',
 'COMPOUND WOMEN TEAM',
 'INDIAN ROUND MEN',
 'INDIAN ROUND MEN INDIVIDUAL',
 'INDIAN ROUND MEN TEAM',
 'INDIAN ROUND MIX TEAM',
 'INDIAN ROUND MIXED TEAM',
 'INDIAN ROUND WOMEN',
 'INDIAN ROUND WOMEN INDIVIDUAL',
 'INDIAN ROUND WOMEN TEAM',
 'RECURVE MEN',
 'RECURVE MEN INDIVIDUAL',
 'RECURVE MEN TEAM',
 'RECURVE MIX TEAM',
 'RECURVE MIXED TEAM',
 'RECURVE WOMEN',
 'RECURVE WOMEN INDIVIDUAL',
 'RECURVE WOMEN TEAM']

In [187]:
event_standardization_dict = {
    "Men's individual recurve": "RECURVE MEN INDIVIDUAL",
    "Men's team recurve": "RECURVE MEN TEAM",
    "Men's team compound": "COMPOUND MEN TEAM",
    "Women's individual recurve": "RECURVE WOMEN INDIVIDUAL",
    "Women's team recurve": "RECURVE WOMEN TEAM",
    "Women's team compound": "COMPOUND WOMEN TEAM",
    'Mixed team recurve': 'RECURVE MIXED TEAM',
    'Mixed team compound': 'COMPOUND MIXED TEAM',
    
    "Men's individual": "INDIVIDUAL MEN",
    "Women's individual": "INDIVIDUAL WOMEN",
    "Men's team": "TEAM MEN",
    "Women's team": "TEAM WOMEN",
    
    "Mixed team" : "MIXED TEAM"
}
df_1['event'] = df_1['event'].map(event_standardization_dict).fillna(df_1['event'])

In [188]:
df_1['event'].unique()

array(['INDIVIDUAL WOMEN', 'INDIVIDUAL MEN', 'TEAM WOMEN', 'TEAM MEN',
       'MIXED TEAM'], dtype=object)

In [189]:
## Standardizing the round names
round_standardization_dict = {
    'Quarterfinals': 'QUARTERFINAL',
    'Semifinals': 'SEMI-FINAL',
    'Gold medal match': 'GOLD MEDAL MATCH',
    'Bronze medal match': 'BRONZE MEDAL MATCH',
    '1/32 eliminations': '1/32 ELIMINATION',
    '1/16 eliminations': '1/16 ELIMINATION',
    '1/8 eliminations': '1/8 ELIMINATION',
    
    
    'Round of 64': "ROUND OF 64", 
    'Round of 32': "ROUND OF 32", 
    'Round of 16': "ROUND OF 16",
    'Quarter-finals': "QUARTER-FINALS",
    'Semi-finals': "SEMI-FINALS", 
    'Gold medal match': "GOLD MEDAL MATCH", 
    'Bronze medal match': "BRONZE MEDAL MATCH",
    '1/32 eliminations': "1/32 ELIMINATION",
    '1/16 eliminations': "1/16 ELIMINATION", 
    '1/8 eliminations': "1/8 ELIMINATION",
    'Quarterfinals': "QUARTERFINAL", 
    'Semifinals': "SEMI-FINAL", 
    'Bronze Medal Match': "BRONZE MEDAL MATCH"
}
df_1['round_name'] = df_1['round_name'].map(round_standardization_dict).fillna(df_1['round_name'])

In [190]:
df_1['round_name'].unique()

array(['ROUND OF 64', 'ROUND OF 32', 'ROUND OF 16', 'QUARTER-FINALS',
       'SEMI-FINALS', 'GOLD MEDAL MATCH', 'BRONZE MEDAL MATCH',
       'Preliminary round', '1/8 ELIMINATION'], dtype=object)

In [191]:
df_1["player_a_countries"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["player_a_countries"] =  df_1["player_a_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1["player_b_countries"] = df_1["player_b"].str.findall(r"\(([^)]*)\)")
df_1["player_b_countries"] =  df_1["player_b_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

df_1["winner_countries"] = df_1["winner"].str.findall(r"\(([^)]*)\)")
df_1["winner_countries"] =  df_1["winner_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

In [192]:
df_1["player_b"] = df_1["player_b"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_b"] = (
    df_1["player_b"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

df_1["player_a"] = df_1["player_a"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_a"] = (
    df_1["player_a"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)


df_1["winner"] = df_1["winner"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["winner"] = (
    df_1["winner"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

In [193]:
## Explode the player_a and player_b columns to have one player per row
df_1 = df_1.assign(
    player_a=df_1["player_a"].str.split(" / ")
).explode("player_a").reset_index(drop=True)

df_1 = df_1.assign(
    player_b=df_1["player_b"].str.split(" / ")
).explode("player_b").reset_index(drop=True)

df_1 = df_1.assign(
    winner=df_1["winner"].str.split(" / ")
).explode("winner").reset_index(drop=True)

In [194]:
df_1['winner'].unique()

array(['Lim S-h', 'R Octavia', 'A Cordeau', 'M Havers', 'Li JM',
       'B Pitman', 'V Marchenko', 'A Valencia', 'E B Gökkır', 'M Fallah',
       'C Lopez', 'S Noda', 'Jeon H-y', 'C Schwarz', 'Lei C-y',
       'C Kaufhold', 'Yang XL', 'L Barbelin', 'A S Caetano',
       'S Mashayikh', 'W Myszor', 'B Kaur', 'C GNoriega', 'D Choirunisa',
       'M Kroppen', 'Y Ramazanova', 'D Kumari', 'Q Roeffen',
       'C Rebagliati', 'M Amăistroaie', 'M Horáčková', 'Nam S-h',
       'Lim Si-hyeon', 'Nam Su-hyeon', 'Lisa Barbelin', 'Kim W-j',
       'Lin Z-s', "M D'Almeida", 'F Saito', 'T Chirault', 'Tai Y-h',
       'Tang C-c', 'M Gazoz', 'Lee W-s', 'A Paoli', 'H Franco', 'Wang Y',
       'A Sadikov', 'M Nespoli', 'E Peters', 'D Bommadevara', 'F Unruh',
       'J Nakanishi', 'C Hall', 'T Hall', 'M Grande', 'J Enríquez',
       'A Wise', 'B Addis', 'B Ellison', 'Kao WC', 'S Wijler', 'B Tümer',
       'S Arcila', 'D Olaru', 'F Musolesi', 'Kim J-d', 'Kim Woo-jin',
       'Brady Ellison', 'Lee Woo-seok', 'Chiu Yi-ching', 'Lei Chien-ying',
       'Li Tsai-chi', 'Quinty Roeffen', 'Gabriela Schloesser',
       'Laura van der Winkel', 'Katharina Bauer', 'Michelle Kroppen',
       'Charline Schwarz', 'Diananda Choirunisa', 'Syifa Nurafifah Kamal',
       'Rezza Octavia', 'Jeon Hun-young', 'Ángela Ruiz',
       'Alejandra Valencia', 'Ana Paula Vázquez', 'An Qixuan',
       'Li Jiaman', 'Yang Xiaolei', 'Takaharu Furukawa',
       'Junya Nakanishi', 'Fumiya Saito', 'Lin Zih-siang', 'Tai Yu-hsuan',
       'Tang Chih-chun', 'Mete Gazoz', 'Berkim Tümer',
       'Abdullah Yıldırmış', 'Federico Musolesi', 'Mauro Nespoli',
       'Alessandro Paoli', 'Kim Je-deok', 'Kao Wenchao', 'Li Zhongyuan',
       'Wang Yan', 'Baptiste Addis', 'Thomas Chirault',
       'Jean-Charles Valladont', 'Chiara Rebagliati',
       'Dhiraj Bommadevara', 'Ankita Bhakat', 'Pablo Acha',
       'Elia Canales', 'Casey Kaufhold', 'Satsuki Noda', 'Matías Grande',
       'Florian Unruh'], dtype=object)

In [195]:
# df_1 = df_1.explode("countries").reset_index(drop=True)
df_1 = df_1.explode("player_b_countries").reset_index(drop=True)
df_1 = df_1.explode("winner_countries").reset_index(drop=True)
df_1 = df_1.explode("player_a_countries").reset_index(drop=True)

In [196]:
df_1['winner_country'] = df_1['winner_countries'].map(COUNTRY__CODES).fillna(df_1['winner_countries'])
df_1['player_b_country'] = df_1['player_b_countries'].map(COUNTRY__CODES).fillna(df_1['player_b_countries'])
df_1['player_a_country'] = df_1['player_a_countries'].map(COUNTRY__CODES).fillna(df_1['player_a_countries'])

In [198]:
df_1['player_b_country'].unique()

array(['PRI', 'IDN', 'SVK', 'ESP', 'DNK', 'MEX', 'TPE', 'GBR', 'MYS',
       'IRN', 'AUS', 'JPN', 'COL', 'USA', 'DEU', 'KOR', 'TUN', 'FRA',
       'SVN', 'POL', 'IND', 'BRA', 'SMR', 'CHN', 'EST', 'AUT', 'ISR',
       'UZB', 'AZE', 'NLD', 'ROU', 'TCD', nan, 'UKR', 'VIR', 'TUR', 'BTN',
       'ARG', 'ITA', 'CAN', 'EGY', 'MNG', 'KAZ', 'LUX', 'MDA'],
      dtype=object)

In [199]:
df_1['winner_country'].unique()

array(['KOR', 'IDN', 'FRA', 'GBR', 'CHN', 'UKR', 'MEX', 'TUR', 'IRN',
       'JPN', 'DEU', 'TPE', 'USA', 'BRA', 'MYS', 'POL', 'IND', 'AZE',
       'NLD', 'ITA', 'ROU', 'CZE', nan, 'CUB', 'UZB', 'CAN', 'COL', 'MDA',
       'ESP'], dtype=object)

In [200]:
df_1[['championship_name', 'event', 'round_name', 'player_a','player_a_country','score_a', 'player_b','player_b_country','score_b', 'winner', 'winner_country']].to_csv('olympics_2024_cleaned.csv', index=False)

In [201]:
df_1 = pd.read_csv('olympics_2021_cleaned.csv')
df_2 = pd.read_csv('olympics_2024_cleaned.csv')
df_3 = pd.read_csv('olympics_2016_cleaned.csv')

In [202]:
df = pd.concat([df_1, df_2, df_3], ignore_index=True)

In [204]:
df.to_csv('consolidated_olympics_results.csv', index=False)

In [205]:
df.columns

Index(['championship_name', 'event', 'round_name', 'player_a',
       'player_a_country', 'score_a', 'player_b', 'player_b_country',
       'score_b', 'winner', 'winner_country'],
      dtype='object')