In [340]:
import pandas as pd

- [ ] Explode on team events

In [341]:
EVENT_NAMES = ['COMPOUND WOMEN INDIVIDUAL',
 'RECURVE MEN INDIVIDUAL',
 'RECURVE WOMEN INDIVIDUAL',
 'COMPOUND MEN INDIVIDUAL',
 'COMPOUND MIXED TEAM',
 'RECURVE MIXED TEAM',
 'RECURVE MEN TEAM',
 'COMPOUND MEN TEAM',
 'RECURVE WOMEN TEAM',
 'COMPOUND WOMEN TEAM',
 'INDIAN ROUND WOMEN TEAM',
 'INDIAN ROUND WOMEN INDIVIDUAL',
 'INDIAN ROUND MEN INDIVIDUAL',
 'INDIAN ROUND MEN TEAM',
 'INDIAN ROUND MIXED TEAM',
 'RECURVE MEN',
 'RECURVE WOMEN',
 'COMPOUND MEN',
 'COMPOUND WOMEN',
 'INDIAN ROUND MEN',
 'INDIAN ROUND WOMEN',
 'RECURVE MIX TEAM',
 'COMPOUND MIX TEAM',
 'INDIAN ROUND MIX TEAM']

ROUND_NAMES = ['1/4 ELIMINATION',
 '1/4 FINAL',
 '1/8 ELIMINATION',
 '1/8 FINAL',
 'BRONZE MEDAL',
 'BRONZE MEDAL MATCH',
 'DATA NOT AVAILABLE',
 'FINAL',
 'GOLD MEDAL MATCH',
 'PRELIMINARY ROUND',
 'QUARTER-FINAL',
 'QUARTERFINAL',
 'ROUND 1',
 'ROUND 2',
 'ROUND OF 12',
 'ROUND OF 16',
 'ROUND OF 24',
 'ROUND OF 32',
 'ROUND OF 48',
 'ROUND OF 64',
 'ROUND OF 8',
 'SEMI-FINAL',
 'SEMIFINAL']


COUNTRY__CODES = {
    # Already codes (keep as-is)
    "KOR": "KOR", "KAZ": "KAZ", "INA": "IDN", "JPN": "JPN",
    "HKG": "HKG", "VIE": "VNM", "NEP": "NPL", "SRI": "LKA",
    "TPE": "TPE", "MYA": "MMR", "QAT": "QAT", "MAS": "MYS",
    "MGL": "MNG", "KSA": "SAU", "IND": "IND", "THA": "THA",
    "BAN": "BGD", "PRK": "PRK", "CHN": "CHN", "SGP": "SGP",
    "PHI": "PHL", "KGZ": "KGZ", "TJK": "TJK", "BHU": "BTN",
    "IRI": "IRN",

    # Full names → ISO3
    "South Korea": "KOR",
    "North Korea": "PRK",
    "India": "IND",
    "China": "CHN",
    "Japan": "JPN",
    "Indonesia": "IDN",
    "Malaysia": "MYS",
    "Iran": "IRN",
    "Kazakhstan": "KAZ",
    "Philippines": "PHL",
    "Thailand": "THA",
    "Hong Kong": "HKG",
    "Chinese Taipei": "TPE",
    
    
    "Mongolia": "MNG",
    "Bangladesh": "BGD",
    "Bhutan": "BTN",
    "Vietnam": "VNM"
}

In [342]:
df_1 = pd.read_csv('asian_games_2018.csv')

# Asian Games 2018

In [343]:
df_1.head()

,championship_name,event,round_name,round,player_a,player_b,score_a,score_b,winner
0,Archery at the 2018 Asian Games,Men's individual recurve,Finals,Quarterfinals,Lee Woo-seok (KOR),Wei Chun-heng (TPE),28,25,Lee Woo-seok (KOR)
1,Archery at the 2018 Asian Games,Men's individual recurve,Finals,Quarterfinals,Khairul Anuar Mohamad (MAS),Ilfat Abdullin (KAZ),27,29,Ilfat Abdullin (KAZ)
2,Archery at the 2018 Asian Games,Men's individual recurve,Finals,Quarterfinals,Riau Ega Agata (INA),Atanu Das (IND),27,27,Riau Ega Agata (INA)
3,Archery at the 2018 Asian Games,Men's individual recurve,Finals,Quarterfinals,Takaharu Furukawa (JPN),Kim Woo-jin (KOR),29,28,Takaharu Furukawa (JPN)
4,Archery at the 2018 Asian Games,Men's individual recurve,Finals,Semifinals,Lee Woo-seok (KOR),Ilfat Abdullin (KAZ),29,27,Lee Woo-seok (KOR)

In [344]:
df_1 = df_1.drop(columns=['round_name'],axis=1)
df_1.rename(columns={'round':'round_name'},inplace=True)

In [345]:
# Clean the event_name
df_1['event'].unique()

array(["Men's individual recurve", "Men's team recurve",
       "Men's team compound", "Women's individual recurve",
       "Women's team recurve", "Women's team compound",
       'Mixed team recurve', 'Mixed team compound'], dtype=object)

In [346]:
event_standardization_dict = {
    "Men's individual recurve": "RECURVE MEN INDIVIDUAL",
    "Men's team recurve": "RECURVE MEN TEAM",
    "Men's team compound": "COMPOUND MEN TEAM",
    "Women's individual recurve": "RECURVE WOMEN INDIVIDUAL",
    "Women's team recurve": "RECURVE WOMEN TEAM",
    "Women's team compound": "COMPOUND WOMEN TEAM",
    'Mixed team recurve': 'RECURVE MIXED TEAM',
    'Mixed team compound': 'COMPOUND MIXED TEAM',
}
df_1['event'] = df_1['event'].map(event_standardization_dict)

In [347]:
## Standardizing the round names
round_standardization_dict = {
    'Quarterfinals': 'QUARTERFINAL',
    'Semifinals': 'SEMI-FINAL',
    'Gold medal match': 'GOLD MEDAL MATCH',
    'Bronze medal match': 'BRONZE MEDAL MATCH',
    '1/32 eliminations': '1/32 ELIMINATION',
    '1/16 eliminations': '1/16 ELIMINATION',
    '1/8 eliminations': '1/8 ELIMINATION'
}
df_1['round_name'] = df_1['round_name'].map(round_standardization_dict).fillna(df_1['round_name'])

In [348]:
df_1["player_a_countries"] = df_1["player_a"].str.findall(r"\(([^)]*)\)")
df_1["player_a_countries"] =  df_1["player_a_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_1["player_b_countries"] = df_1["player_b"].str.findall(r"\(([^)]*)\)")
df_1["player_b_countries"] =  df_1["player_b_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

df_1["winner_countries"] = df_1["winner"].str.findall(r"\(([^)]*)\)")
df_1["winner_countries"] =  df_1["winner_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

In [349]:
df_1["player_b"] = df_1["player_b"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_b"] = (
    df_1["player_b"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

df_1["player_a"] = df_1["player_a"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["player_a"] = (
    df_1["player_a"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)


df_1["winner"] = df_1["winner"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_1["winner"] = (
    df_1["winner"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

In [350]:
## Explode the player_a and player_b columns to have one player per row
df_1 = df_1.assign(
    player_a=df_1["player_a"].str.split(" / ")
).explode("player_a").reset_index(drop=True)

df_1 = df_1.assign(
    player_b=df_1["player_b"].str.split(" / ")
).explode("player_b").reset_index(drop=True)

df_1 = df_1.assign(
    winner=df_1["winner"].str.split(" / ")
).explode("winner").reset_index(drop=True)

In [351]:
# df_1 = df_1.explode("countries").reset_index(drop=True)
df_1 = df_1.explode("player_b_countries").reset_index(drop=True)
df_1 = df_1.explode("winner_countries").reset_index(drop=True)
df_1 = df_1.explode("player_a_countries").reset_index(drop=True)

In [352]:
df_1['winner_country'] = df_1['winner_countries'].map(COUNTRY__CODES).fillna(df_1['winner_countries'])
df_1['player_b_country'] = df_1['player_b_countries'].map(COUNTRY__CODES).fillna(df_1['player_b_countries'])
df_1['player_a_country'] = df_1['player_a_countries'].map(COUNTRY__CODES).fillna(df_1['player_a_countries'])

In [353]:
df_1

,championship_name,event,round_name,player_a,player_b,score_a,score_b,winner,player_a_countries,player_b_countries,winner_countries,winner_country,player_b_country,player_a_country
0,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Lee Woo-seok,Wei Chun-heng,28,25,Lee Woo-seok,KOR,TPE,KOR,KOR,TPE,KOR
1,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Khairul Anuar Mohamad,Ilfat Abdullin,27,29,Ilfat Abdullin,MAS,KAZ,KAZ,KAZ,KAZ,MYS
2,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Riau Ega Agata,Atanu Das,27,27,Riau Ega Agata,INA,IND,INA,IDN,IND,IDN
3,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Takaharu Furukawa,Kim Woo-jin,29,28,Takaharu Furukawa,JPN,KOR,JPN,JPN,KOR,JPN
4,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,SEMI-FINAL,Lee Woo-seok,Ilfat Abdullin,29,27,Lee Woo-seok,KOR,KAZ,KOR,KOR,KAZ,KOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2582,Archery at the 2018 Asian Games,COMPOUND WOMEN TEAM,BRONZE MEDAL MATCH,Fereshteh Ghorbani,Lin Ming-ching,221,226,Lin Ming-ching,Iran,Chinese Taipei,Chinese Taipei,TPE,TPE,IRN
2583,Archery at the 2018 Asian Games,RECURVE MIXED TEAM,GOLD MEDAL MATCH,Takaharu Furukawa,Kim Kuk-song,36,35,Takaharu Furukawa,Japan,North Korea,Japan,JPN,PRK,JPN
2584,Archery at the 2018 Asian Games,RECURVE MIXED TEAM,GOLD MEDAL MATCH,Ayano Kato,Kang Jin-hwa,36,35,Ayano Kato,Japan,North Korea,Japan,JPN,PRK,JPN
2585,Archery at the 2018 Asian Games,COMPOUND MIXED TEAM,GOLD MEDAL MATCH,Choi Yong-hee,Chen Hsiang-hsuan,150,151,Chen Hsiang-hsuan,South Korea,Chinese Taipei,Chinese Taipei,TPE,TPE,KOR
2586,Archery at the 2018 Asian Games,COMPOUND MIXED TEAM,GOLD MEDAL MATCH,Choi Bo-min,Chen Li-ju,150,151,Chen Li-ju,South Korea,Chinese Taipei,Chinese Taipei,TPE,TPE,KOR

In [354]:
df_1[['championship_name', 'event', 'round_name', 'player_a','player_a_country','score_a', 'player_b','player_b_country','score_b', 'winner', 'winner_country']].to_csv('asian_games_2018_cleaned.csv', index=False)

In [355]:
# df_1.to_csv('asian_games_2018_cleaned.csv', index=False)

# Asian Games 2022

In [356]:
df_2 = pd.read_csv('asian_games_2022.csv')

In [357]:
df_2 = df_2.drop(columns=['round_name'],axis=1)
df_2.rename(columns={'round':'round_name'},inplace=True)

In [358]:
# Clean the event_name
df_2['event'].unique()

array(["Men's individual recurve", "Men's individual compound",
       "Men's team recurve", "Men's team compound",
       "Women's individual recurve", "Women's individual compound",
       "Women's team recurve", "Women's team compound",
       'Mixed team recurve', 'Mixed team compound'], dtype=object)

In [359]:
event_standardization_dict = {
    "Men's individual recurve": "RECURVE MEN INDIVIDUAL",
    "Men's team recurve": "RECURVE MEN TEAM",
    "Men's team compound": "COMPOUND MEN TEAM",
    "Women's individual recurve": "RECURVE WOMEN INDIVIDUAL",
    "Women's team recurve": "RECURVE WOMEN TEAM",
    "Women's team compound": "COMPOUND WOMEN TEAM",
    'Mixed team recurve': 'RECURVE MIXED TEAM',
    'Mixed team compound': 'COMPOUND MIXED TEAM',
    
    "Men's individual compound" : "COMPOUND MEN INDIVIDUAL",
    "Women's individual compound" : "COMPOUND WOMEN INDIVIDUAL"
    
    
}
df_2['event'] = df_2['event'].map(event_standardization_dict).fillna(df_2['event'])

In [360]:
df_2['round_name'].unique()

array(['Quarterfinals', 'Semifinals', 'Gold medal match',
       'Bronze medal match', '1/32 eliminations', '1/16 eliminations',
       '1/8 eliminations'], dtype=object)

In [361]:
## Standardizing the round names
round_standardization_dict = {
    'Quarterfinals': 'QUARTERFINAL',
    'Semifinals': 'SEMI-FINAL',
    'Gold medal match': 'GOLD MEDAL MATCH',
    'Bronze medal match': 'BRONZE MEDAL MATCH',
    '1/32 eliminations': '1/32 ELIMINATION',
    '1/16 eliminations': '1/16 ELIMINATION',
    '1/8 eliminations': '1/8 ELIMINATION'
}
df_2['round_name'] = df_2['round_name'].map(round_standardization_dict).fillna(df_2['round_name'])

In [362]:
df_2["player_a_countries"] = df_2["player_a"].str.findall(r"\(([^)]*)\)")
df_2["player_a_countries"] =  df_2["player_a_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)


df_2["player_b_countries"] = df_2["player_b"].str.findall(r"\(([^)]*)\)")
df_2["player_b_countries"] =  df_2["player_b_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

df_2["winner_countries"] = df_2["winner"].str.findall(r"\(([^)]*)\)")
df_2["winner_countries"] =  df_2["winner_countries"].apply(lambda x: list(set(x)) if isinstance(x, list) else x)

In [363]:
df_2["player_b"] = df_2["player_b"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_2["player_b"] = (
    df_2["player_b"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

df_2["player_a"] = df_2["player_a"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_2["player_a"] = (
    df_2["player_a"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)


df_2["winner"] = df_2["winner"].str.replace(r"\s*\([^)]*\)", "", regex=True)
df_2["winner"] = (
    df_2["winner"]
    .str.replace(r"\s*\([^)]*\)", "", regex=True)
    .str.replace(r"\s*/\s*", " / ", regex=True)  # normalize separators
    .str.strip()
)

In [364]:
## Explode the player_a and player_b columns to have one player per row
df_2 = df_2.assign(
    player_a=df_2["player_a"].str.split(" / ")
).explode("player_a").reset_index(drop=True)

df_2 = df_2.assign(
    player_b=df_2["player_b"].str.split(" / ")
).explode("player_b").reset_index(drop=True)

df_2 = df_2.assign(
    winner=df_2["winner"].str.split(" / ")
).explode("winner").reset_index(drop=True)

In [365]:
# df_1 = df_1.explode("countries").reset_index(drop=True)
df_2 = df_2.explode("player_b_countries").reset_index(drop=True)
df_2 = df_2.explode("winner_countries").reset_index(drop=True)
df_2 = df_2.explode("player_a_countries").reset_index(drop=True)

In [366]:
df_2['winner_country'] = df_2['winner_countries'].map(COUNTRY__CODES).fillna(df_2['winner_countries'])
df_2['player_b_country'] = df_2['player_b_countries'].map(COUNTRY__CODES).fillna(df_2['player_b_countries'])
df_2['player_a_country'] = df_2['player_a_countries'].map(COUNTRY__CODES).fillna(df_2['player_a_countries'])

In [367]:
df_2[['championship_name', 'event', 'round_name', 'player_a','player_a_country','score_a', 'player_b','player_b_country','score_b', 'winner', 'winner_country']].to_csv('asian_games_2022_cleaned.csv', index=False)

In [369]:
df = pd.concat([df_1, df_2], ignore_index=True)
df

,championship_name,event,round_name,player_a,player_b,score_a,score_b,winner,player_a_countries,player_b_countries,winner_countries,winner_country,player_b_country,player_a_country
0,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Lee Woo-seok,Wei Chun-heng,28,25,Lee Woo-seok,KOR,TPE,KOR,KOR,TPE,KOR
1,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Khairul Anuar Mohamad,Ilfat Abdullin,27,29,Ilfat Abdullin,MAS,KAZ,KAZ,KAZ,KAZ,MYS
2,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Riau Ega Agata,Atanu Das,27,27,Riau Ega Agata,INA,IND,INA,IDN,IND,IDN
3,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,QUARTERFINAL,Takaharu Furukawa,Kim Woo-jin,29,28,Takaharu Furukawa,JPN,KOR,JPN,JPN,KOR,JPN
4,Archery at the 2018 Asian Games,RECURVE MEN INDIVIDUAL,SEMI-FINAL,Lee Woo-seok,Ilfat Abdullin,29,27,Lee Woo-seok,KOR,KAZ,KOR,KOR,KAZ,KOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6085,Archery at the 2022 Asian Games,COMPOUND MIXED TEAM,SEMI-FINAL,Chen Li-ju,Cho Su-a,153,158,Cho Su-a,Chinese Taipei,South Korea,South Korea,KOR,KOR,TPE
6086,Archery at the 2022 Asian Games,COMPOUND MIXED TEAM,GOLD MEDAL MATCH,Rajat Chauhan,Choi Yong-hee,159,158,Rajat Chauhan,India,South Korea,India,IND,KOR,IND
6087,Archery at the 2022 Asian Games,COMPOUND MIXED TEAM,GOLD MEDAL MATCH,Avneet Kaur,Cho Su-a,159,158,Avneet Kaur,India,South Korea,India,IND,KOR,IND
6088,Archery at the 2022 Asian Games,COMPOUND MIXED TEAM,BRONZE MEDAL MATCH,Akbarali Karabayev,Chang Cheng-wei,154,157,Chang Cheng-wei,Kazakhstan,Chinese Taipei,Chinese Taipei,TPE,TPE,KAZ
6089,Archery at the 2022 Asian Games,COMPOUND MIXED TEAM,BRONZE MEDAL MATCH,Viktoriya Lyan,Chen Li-ju,154,157,Chen Li-ju,Kazakhstan,Chinese Taipei,Chinese Taipei,TPE,TPE,KAZ

In [370]:
df_2[['championship_name', 'event', 'round_name', 'player_a','player_a_country','score_a', 'player_b','player_b_country','score_b', 'winner', 'winner_country']].to_csv('asian_games_consolidated_cleaned.csv', index=False)